name: Metrics
on:
  # Updates daily at midnight
  schedule: [ { cron: "0 0 * * *" } ]
  workflow_dispatch:
  push: { branches: [ "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_BOT }}

          # Options
          user: Colin23
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_repositories: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_threshold: 5%
          # …add other plugins as desired…
