name: Metrics
on:
  # Updates every 12 hours
  schedule: [ { cron: "0 */12 * * *" } ]
  workflow_dispatch:
  push: { branches: [ "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_BOT }}

          # Options
          user: Colin23
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_activity: yes
          plugin_repositories: yes
          # …add other plugins as desired…
